CREATE TABLE JM3200104_CUSTOMER_TBL(
CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(55),
LAST_NAME VARCHAR(55),
AGE NUMBER,
GENDER VARCHAR(10),
ADDRESS VARCHAR(255),
OCCUPATION VARCHAR(255)
)