CREATE TABLE JM3200104_ONETOONE_BI_RESULT(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
STATUS VARCHAR
);

CREATE TABLE JM3200104_ONETOONE_BI_TRAINEE(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR,
RESULT_ID BIGINT,
FOREIGN KEY(RESULT_ID) REFERENCES JM3200104_ONETOONE_BI_RESULT(ID)
);

