CREATE TABLE JM3200104_OTM_UNI_COURSE(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR
);

CREATE TABLE JM3200104_OTM_UNI_ASSIGNMENT(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR,
COURSE_ID BIGINT,
FOREIGN KEY(COURSE_ID) REFERENCES JM3200104_OTM_UNI_COURSE(ID)
);