CREATE TABLE JM3200104_EMPLOYEE(id BIGINT PRIMARY KEY, NAME VARCHAR(55), AGE NUMBER);


CREATE TABLE JM3200104_EMPLOYEE_IDENTITY(id BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(55), AGE NUMBER);